In [9]:
import pandas as pd 
from sklearn import svm
from sklearn.model_selection import train_test_split
df_new = pd.read_csv('letterdata.csv')

In [2]:
df_new

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [3]:
y = df_new['letter']
x = df_new.drop('letter',axis = 1)

In [4]:
y

0        T
1        I
2        D
3        N
4        G
        ..
19995    D
19996    C
19997    T
19998    S
19999    A
Name: letter, Length: 20000, dtype: object

In [5]:
x

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [10]:
clf = svm.SVC()

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x , y ,test_size=0.3, random_state=1)

In [12]:
clf.fit(x_train,y_train)

SVC()

In [13]:
y_pred = clf.predict(x_test)

In [14]:
clf.score(x_test,y_test)

0.9168333333333333

In [15]:
a = pd.crosstab(y_test,y_pred)

In [16]:
a

col_0,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
letter,,,,,,,,,,,,,,,,,,,,,
A,224,0,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
B,1,216,0,5,1,1,3,0,0,0,...,0,11,1,0,0,0,0,2,0,0
C,0,0,205,0,8,0,4,0,0,0,...,0,0,0,0,1,0,0,0,0,0
D,0,7,0,220,0,0,0,1,0,0,...,0,3,0,0,0,0,0,0,0,0
E,0,2,0,0,195,0,11,0,0,0,...,1,1,1,0,0,0,0,1,0,2
F,0,2,0,1,2,201,2,1,3,0,...,0,0,0,4,0,0,0,0,0,0
G,0,0,3,3,2,1,203,0,0,0,...,3,1,0,0,0,1,3,0,0,0
H,0,8,0,10,0,2,1,182,0,0,...,1,16,0,0,2,2,0,1,2,0
I,0,0,1,3,0,3,0,0,183,6,...,0,0,0,0,0,0,0,2,0,1
J,0,0,0,2,1,1,0,2,7,178,...,0,0,5,0,0,0,0,1,0,0
K,0,1,1,1,2,0,0,2,0,0,...,0,6,0,0,0,0,0,4,0,0
L,0,2,2,0,7,0,2,1,0,0,...,0,3,1,0,0,0,0,3,0,0
M,0,2,0,0,0,0,1,0,0,0,...,0,2,0,0,0,0,1,0,0,0
N,0,2,0,5,0,0,0,3,0,0,...,0,3,0,0,0,0,0,0,0,0
O,0,0,0,8,0,0,0,0,0,0,...,7,3,0,0,2,0,10,0,0,0
P,0,1,0,4,0,18,9,2,1,0,...,1,2,0,0,0,0,0,0,3,0
Q,1,0,0,0,0,0,2,1,0,0,...,228,0,1,0,0,0,0,0,0,0
R,0,8,0,3,2,0,0,1,0,0,...,0,201,0,0,0,0,0,0,0,0
S,0,8,0,0,3,2,1,0,0,0,...,0,2,239,0,0,0,0,0,0,1
T,0,1,0,1,1,0,8,6,0,0,...,0,1,1,226,0,0,0,2,0,0
U,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,230,0,3,0,0,0
V,2,8,0,1,0,0,0,0,0,0,...,0,1,0,0,0,202,4,0,0,0
W,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,220,0,0,0
X,0,0,0,5,3,0,0,0,0,1,...,1,0,0,0,0,0,0,220,1,0
Y,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,1,251,0
Z,1,0,0,0,3,0,0,0,0,0,...,1,0,3,0,0,0,0,0,0,226